### ISSUE TITLE
Vision Document

### ISSUE THREAD

**Issue by CharliePoole** [nunit/governance#10]
I propose that the vision document, which is now part of our developer docs on the wiki, be moved to the governance repo and that we review and revise it as needed.

If folks agree, I'll make a PR and we can then comment on it line by line if we need to.

**Comment by rprouse** [comment]
Agreed and I think a PR is the best way to do it.

**Comment by ChrisMaddock** [comment]
Sounds good.

**Comment by CharliePoole** [comment]
Hmm... I'll do it that way if you guys like, but it seems like it would (a) be more work because I would have to do all the editing elsewhere and (b) would hide from review (or make it harder) the changes I make to the document. It makes much more sense to me to just add it, since it's already our published document, and then use a PR for the changes.

**Comment by ChrisMaddock** [comment]
@CharliePoole - I assumed you wanted us to comment on the existing document, prior to any changes. If you're instead intending to propose changes, then your second proposal sounds more sensible - although it would be good to review the entire document, rather than just any proposed changes, if we're adding it here.

**Comment by CharliePoole** [comment]
@ChrisMaddock Sure. But we should bear in mind that the document as it stands is __already__ our policy. I assumed everyone was already familiar with it... just kidding. 😈

What I'll do is use the PR in both cases. When I add it, I'll do it with comments about what I hope to change.  Then we can discuss my ideas before I carry them out. We shouldn't need to have a vote to merge it as is. Next, I'll make the changes and do another PR. Does that suit?

**Comment by ChrisMaddock** [comment]
Sounds good.
