### ISSUE TITLE
More communicative name for the Core Team

### ISSUE THREAD

**Issue by jnm2** [nunit/governance#17]
We all know that naming is one of the two hardest things in software development (along with cache invalidation, and off-by-one errors).

I've come to think that communication between ourselves, other teams and outside contributors would benefit from choosing a more intuitive and transparent name than 'Core Team.' For example, we'll talk about the core projects. Is the Core Team simply the team that works on the core projects? No, but that's a natural intuition. Can we set up a new name to help people fall into the so-called pit of success in understanding the Core Team?

Ideas:

 - Governance team
 - Guidance team
 - Vision team
 - Admin team
 - Supervision team
 - Steering team

Suggestions?

We won't be able to get across the entire description of what we are in one word, so let's shoot for the most accurate description and the most important connotations.

**Comment by CharliePoole** [comment]
FWIW I haven't liked Core Team for a while but hung on to it because the name works whether the team is a central authority or a court of last resort or the keepers of the Vision...

In software, not having a good name often means you haven't yet figured out what something does.

**Comment by OsirisTerje** [comment]
Frankly I like the name Core team.  I have used it a few times with people, and everyone immediately understands what it means - this is the group of people that are closest to the NUnit work, and is the main people working with it, the people that are the "core" of  NUnit, and who takes "care" of NUnit.  The caretakers so to speak.    
Core projects however, doesn't ring a bell mostly.  People see NUnit as an organization, and whatever is inside there is sort of NUnit.    
The word Core is short, quickly said too.   Long names like most of those  @jnm2 suggests above, are not that good, hard to say, some sounds like management stuff, imho.  

Alternatives I can figure out is not that good,   Central team....  nah....     Main team   nah2......    Master team...   nah3,,,,,   "Keepers of the Crypt"  --- rofl...  not....   (although the latest sounds much closer, it cant be used seriously)

Note that the name should  be externally used, so references to our own governance and so on doesn't ring with me.   It should be short (4-6 letters,  1 syllable) 

Imho, I would stay with Core team.

**Comment by CharliePoole** [comment]
@OsirisTerje That's brilliant!

So the problem is not with Core Team but with Core Projects! Thinking about it, I agree with you. That word is what made it hard for me to consider the adapter as "core" because it's not the heart of what makes NUnit work. But it's an important, key, strategic (add your own word) project for sure.

I'm in favor of keeping Core Team, which is about people and finding a new way to talk about our strategic projects. I vote for Strategic right now, but maybe somebody has a better idea.

**Comment by rprouse** [comment]
I am also good with Core Team, but agree that we should start referring to the core projects differently to prevent confusion. Strategic projects covers the meaning, but is a bit hard to say and I'm not sure many people will understand. Main, prime, primary, principal?

**Comment by CharliePoole** [comment]
Strategic came out of my days at Microsoft. I had a boss on Picture It! , a Microsoft old-timer with a very low employee number, who used to say that the last thing you wanted was for your project to be considered strategic. Once that happened, Bill would be all over you. 😄 

It works for me but maybe that's just my experience. Key may be an option too. Main sounds like an umbrella that contains other projets. Prime et al are a bit more generic in my mind, but that may be because I've heard Strategic and Key used for categorizing product lines before in my career. It seems to me that Strategic is used a lot by product line managers.

Primary does play nicely against Secondary, which we already have.

**Comment by jnm2** [comment]
How about 'central projects'? What we have is kind of like a graph with a few interconnected projects in the center and other projects more loosely connected to the central projects.

**Comment by jnm2** [comment]
I like primary too.

**Comment by rprouse** [comment]
@jnm2 I like central and the graph image that it invokes. 👍

**Comment by CharliePoole** [comment]
So does Central / Secondary work? or do we have to change Secondary as well?

**Comment by CharliePoole** [comment]
@Can we decide and then update governance.md and projects.md?

**Comment by jnm2** [comment]
I'm fine with central/secondary.

**Comment by CharliePoole** [comment]
I like Primary / Secondary if we don't want Strategic.

**Comment by ChrisMaddock** [comment]
My favourite of what's been suggested would be "Key Projects" (And Secondary Projects). I'd be happy with central/secondary, then primary/secondary - in that order. @CharliePoole - as I think you are trying to tie this up - please consider me happy with any of those.

I'm afraid I'm not a fan of 'strategic' - perhaps it's just not a term I'm used to. 🙂

**Comment by ChrisMaddock** [comment]
And in response to the earlier comments - I like 'core team', as a well-recognised term for the 'main guys' in an open source project. I'm not sure how we want to use it is strictly the conventional use, which is perhaps more 'core committers', but that doesn't worry me too much. In other words - I agree with Terje. 😄

**Comment by CharliePoole** [comment]
Trying to tie this up...

1. I think the consensus is that we keep Core Team.

2. Everybody has a different favorite for projects. My take is that Key Projects / Secondary Projects displeases the fewest people. Can we agree to go with that?

**Comment by jnm2** [comment]
So when writing documentation we use the terms 'key' and 'secondary' for consistency, and when speaking amongst each other, it probably doesn't matter a whole lot. At least not in the same way as the label used to refer to our team.

And I like Core Team, too, now that I know it has the correct connotations and is recognized as an OSS term.

I appreciate each of your input.

**Comment by CharliePoole** [comment]
@jnm2 We haven't done a PR to change the docs yet
