### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by rprouse** [nunit/governance#18]
I believe that we should have a code of conduct. The [recommendation](https://opensource.guide/how-to-contribute/#anatomy-of-an-open-source-project) is to add a `CODE_OF_CONDUCT.md` file in each repository, although we could link to a document in this repository from that file. Having the file would allow us to complete the [Community Standards](https://github.com/nunit/nunit/community) checklist for each repository.

If we are planning or even just thinking of joining the .NET Foundation, we could just adopt their [code of conduct](https://dotnetfoundation.org/code-of-conduct).

We could also select one of GitHub's supplied [Code of Conduct Templates](https://help.github.com/articles/adding-a-code-of-conduct-to-your-project/). I haven't read through them yet, so I don't have an opinion on them.

**Comment by CharliePoole** [comment]
Sounds like a good idea but it could mean a lot of different things. For example, I've written codes of conduct that apply to sexual discrimination, bullying and changing people's code without reason. These are all quite different things. What kind do we mean here.

I tried the link, but it's not clear how one could read through the various Codes of Conduct supported by the templates without actually adding them first.

**Comment by jnm2** [comment]
I vote we just adopt the .NET Foundation's code of conduct which is actually the http://contributor-covenant.org/ unless we have a specific criterion it doesn't meet.

(If we do that, we should add our name to http://contributor-covenant.org/adopters/.)

**Comment by jnm2** [comment]
If we do that, we should add our name to http://contributor-covenant.org/adopters/.

**Comment by ChrisMaddock** [comment]
I think the .NET Foundation version covers our needs.

**Comment by CharliePoole** [comment]
I favor the Contributor Covenant, which is what the .NET foundation adopted / adapted. I guess the adaptation part is adding a contact. @rprouse Since you proposed, will you do a PR?

**Comment by jnm2** [comment]
<sup>(I want to see what Terje thinks too.)</sup>

**Comment by CharliePoole** [comment]
I think this PR requires a vote.

**Comment by rprouse** [comment]
I have assigned to myself and will do a PR. I will add the code of conduct to this repository and then once we approve, we can add `CODE_OF_CONDUCT.md` files to each of our main repositories with a link back to the canonical version here.
