### ISSUE TITLE
Website contents

### ISSUE THREAD

**Issue by CharliePoole** [nunit/governance#22]
Issue nunit/nunit.org#57 is about transitioning the website.

My general plan is to turn over nunit.org to the project and use nunit.com for my commercial work. Right now they all point to the same thing, so that will have to change.

In order to even do a plan or proposal, I need a few bits of info from the Core Team.

1. Do you want to maintain the legacy docs? If not, I'll keep them on nunit.com. They use old technology and are not changed except when we notice something __very__ wrong. I would just keep them there as a service.

2. Current cost is $4 per month for hosting and about $15 per year for the .org domain. That could be taken on by somebody else or NUnit Software could be a sponsor and keep carrying it for a while. I'm assuming that you will want to convert the hosting to GitHub, but that might not be an instant thing.

3. Does somebody want to volunteer as the webmaster? That will be easier than asking the entire team about each little step we have to take.

Of course, I'm asking this stuff as one guy to the Core Team. I'll put on my core team hat when we discuss it. 😄

**Comment by rprouse** [comment]
I am happy to take on the costs of hosting and the domain. If we join the .NET Foundation, they can help with that, but it isn't enough money for me to worry about. I can also use my Azure credits for hosting, or we can switch to a GitHub site and get the hosting for free. We already have an experimental site here in the organization. https://github.com/nunit/nunit.github.io and http://nunit.github.io/

I would like to migrate to that, but we should discuss if it meets our needs. If we do go with GitHub.io, we probably don't need a webmaster since updates happen automatically through PRs.

 As for the legacy documentation, I find the numerous versions to be excessive. I think we should just figure out a way to export the 2.6.4 documentation and leave it at that. The docs are generally fairly clear which version of NUnit features were released in, so that seems good enough to me.

Even if you continue to host the docs on NUnit.com, all existing links to those docs likely go to NUnit.org, so they will become broken. Because of that, I don't see the need for the older docs and I actually like the idea of breaking some of those old links because they are so outdated.

**Comment by rprouse** [comment]
For the GitHub.io site, I think the big objections previously was re-instating @CharliePoole's blog on the site and maintaining documentation. I assume the blog will go to NUnit.com and we can make a call on the documentation. Is there anything else we should consider?

**Comment by CharliePoole** [comment]
That's enough info for me to get started. I'll split things up a bit and there will be time to review as you move to GitHub or another location. It can also stay on AcornHost for a time while we work on it. The "webmaster" job I was thinking of was basically doing design, managing the DNS and the hosting. I guess that will be you at least initially.

**Comment by jnm2** [comment]
Whatever we do with hosting, I would like to hold open the possibility of migrating our wiki to the NUnit website.

**Comment by ChrisMaddock** [comment]
I'd like to see us put reasonable effort into keeping the legacy docs online and not breaking links - whether that's retaining the current URLs, or putting in some sort of URL forwarding solution. I imagine there will be hundreds of links to those docs pages littered across the internet by now. Unfortunately, the how-to of that really isn't my area! (This is also an 'ideal' - I'm becoming very aware we have many ideal's we're unlikely to be able to do!)

On cost and hosting - great if either Rob or NUnit Software are willing to look after this in the short-term, although I think we should look for a more sustainable solution in the long-term. GitHub is the obvious choice for hosting - as other people have said, .NET Foundation would be one solution for this also.

I'd also like the see the nunit.org domain, point to the pages currently at nunit.github.io - I think it would be good to have a more modern homepage for the NUnit 3 era. I imagine there's some bits and pieces to do to make sure all the content from the old site is replicated on the new - but I think that would be a good direction to move in.

> Whatever we do with hosting, I would like to hold open the possibility of migrating our wiki to the NUnit website.

Absolutely agree, for a 'one-day' project. Just need someone willing to take a stab at it, like so much. 😄

**Comment by ChrisMaddock** [comment]
A request - nunit.com is a domain which has pointed to the same as nunit.org for a long time. Again, thinking of historical links, I imagine there will be many which point to nunit.com. 

Would it be possible to maintain a clear link from nunit.com to nunit.org, once .com is being used for a different purpose?

**Comment by CharliePoole** [comment]
Thanks @ChrisMaddock both are good suggestions.

**Comment by CharliePoole** [comment]
Thinking it over, I'm not sure whether I will have a need for nunit.com. It depends on that business plan that I'm not yet ready to do. So I'm thinking I'll keep all the domains for now - they don't expire till next year anyway - and manage the DNS to point all three to the same place. 

When we are ready to go to GitHub, I'll change all three to point there. I'll also take some steps to be able to measure the use of nunit.com. It's now set up as an A record (alias), so I don't get the stats. I'll change it to a CNAME (forward) and I think I'll be able to collect stats separately for each TLD.

If I never have a need for nunit.com, all three can eventually be turned over to either Rob or the .NET Foundation. If I decide to hang on to it, there will be time to figure out what that means and allow for it.

I've added a checklist of steps to be taken to nunit/nunit.org#57. As you will see, the blog is no longer in the header, although I haven't cleaned out the files yet.

**Comment by ChrisMaddock** [comment]
@CharliePoole - can we close this one? 😄

**Comment by rprouse** [comment]
The website is now hosted by GitHub and I manage the domains and DNS, so I think we can close. If there is something missing, please comment and reopen.
