### ISSUE TITLE
Decide what to do about the 3rdparty-runners list

### ISSUE THREAD

**Issue by CharliePoole** [nunit/governance#28]
We have not been using this list for a while - since the 3.0 release I think. We should either kill it or create something elsewhere.

**Comment by ChrisMaddock** [comment]
List, as in mailing list? Whereabouts is this list?

Definitely sounds useful. 😄

**Comment by CharliePoole** [comment]
Yes, mailing list. We set it up to give info to third-party runner authors and get feedback from them. The archives are here: https://cpanel.nunit.org/cpsess1527946816/3rdparty/mailman/private/3rdparty-runners_nunit.org/ 

Not sure if you have to be a member to see it. In case you can't, the last post was in February 2016.

My own view is that this list was not very useful. Vendors tend not to want to share any info on a list that has other vendors on it. Also, Microsoft never participated, even though invited. I guess it's hard for them to think of themselves as "third party." 😸 

Looking at that list, I realized we also have an nunit-committers mailing list. That was used for precisely one thread, back in 2015. I'm going to delete that one, but I think the 3rdparty-runners list is worth a brief discussion first.

**Comment by jnm2** [comment]
I think we can safely kill it in favor of our other channels of communication. A distinction won't be helpful unless there is so much traffic it deserves its own channel.

**Comment by rprouse** [comment]
I say we kill it. If anyone wants to talk 3rdParty runners, they can do it on the developers list.

**Comment by CharliePoole** [comment]
I'll send a notice on it and then delete it.

**Comment by CharliePoole** [comment]
I sent the final messages but as sender I don't think I'll see them. Somebody post when you see either one please.

**Comment by CharliePoole** [comment]
Finally got back an undeliverable notice. I guess this got messed up with all the DNS changes. It seems silly to fix it so I can send the notices and then immediately delete it. I'm just moving ahead with the deletion.
