### ISSUE TITLE
Decide on Project to Contribute to the .NET Foundation

### ISSUE THREAD

**Issue by rprouse** [nunit/governance#29]
We've agreed in #27 to contribute all of our primary and secondary project to the .NET Foundation under a contribution agreement and not contribute archived projects. That issue is getting long, so I am starting a clean one so that we can confirm the project list and make sure I didn't make any mistakes. Once we confirm, I will send the list to Jon.

I am working off of the [NUnit Software Projects](https://github.com/nunit/governance/blob/master/projects.md) list. I am also assuming that the @nunit/core-team will sign the contribution agreement for all projects except for the TD.NET adapter which @jcansdale will sign for.

I generated the full list of the repositories for the org using the GitHub API so that nothing was missed. **Does this breakdown look correct? Should anything be moved between the lists?**

## Projects to be Contributed to the .NET Foundation

| Repository | Project | Signatories |
| ---------- | ------- | ----------- |
| nunit | NUnit Framework | Core Team |
| nunit-console | NUnit Console and Engine | Core Team |
| nunit-vs-adapter | NUnit 2 Visual Studio Adapter | Core Team |
| nunit3-vs-adapter | NUnit 3 Visual Studio Adapter | Core Team |
| nunit-v2-framework-driver | NUnit V2 Framework Driver | Core Team |
| nunit-v2-result-writer | NUnit V2 Result Writer | Core Team |
| nunit-project-loader | NUnit Project Loader | Core Team |
| vs-project-loader | VS Project Loader | Core Team |
| nunit.xamarin | NUnit Xamarin Runner | Core Team |
| nunit.github.io | NUnit Website | Core Team |
| nunit-distribution | NUnit installer | Core Team |
| nunit-vs-templates | NUnit VS Templates | Core Team |
| docs | NUnit Documentation | Core Team |
| resources | Images and Icons | Core Team |
| governance | Organization Governance | Core Team |
| nunit-csharp-samples | C# Samples | Core Team |
| nunit-fsharp-samples | F# Samples | Core Team |
| nunit-vb-samples | VB.NET Samples | Core Team |
| nunit-cpp-samples | C++ Samples | Core Team |
| nunit-vs-testgenerator | NUnit VS Test Generator | Core Team |
| nunit3-tdnet-adapter | NUnit Adapter for TD.NET | Jamie Cansdale <jcansdale@gmail.com> |

## Projects that will not be contributed

| Repository | Project | Comments |
| ---------- | ------- | ----------- |
| NUnit.System.Linq | LINQ Compatibility code for NUnit | Mono Code, already in the Foundation |
| nunitlite | NUnitLite v1 | Archived |
| nunitv2 | NUnit v2 | Archived |
| nunit.org | Old NUnit Website | Archived |
| nunit-transforms | NUnit | Archived |
| dotnet-test-nunit | Old .NET Core Adapter | Archived |
| nunit.portable.agent | Common code for old .NET Core Adapter | Archived |
| nunit-silverlight | NUnit for Silverlight | Archived |
| nunit-compactframework | NUnit for Compact Framework | Archived |
| nunit.analyzers | Rosyln Analyzers | Pre-Release |
| nunit-expectations | AssertHelper | Pre-Release |
| teamcity-event-listener | TeamCity Adapter | Eventually moving to JetBrains |

**Comment by OsirisTerje** [comment]
The nunit-vs-testgenerator should be contributed.  It originally came from MS, so just natural that it follows along.

I would also love to see the NUnit.Analyzers moving along,  I know it doesn’t have much progress, but the idea and skeleton makes sense.  It is early, but still……


Regards
Terje

**Comment by rprouse** [comment]
I agree about the test generator, but wasn't sure if we have the right to sign for it. It was donated to us, but without any documentation.

As for the Anayzers, the plan is that pre-release projects will be turned over when they are ready. I like the idea too, but there hasn't been any activity on the project recently.

**Comment by ChrisMaddock** [comment]
This list looks good to me. 👍

**Comment by CharliePoole** [comment]
My only question is about NUnit.System.Linq. I don't think that code is ours to contribute.

**Comment by CharliePoole** [comment]
One more question. Doesn't the foundation make a distinction between the primary copyright holders and other contributors? Do they want both to sign the same thing? What about other contributors beyond the core team? Have you gotten any guidance on this from the foundation folks?

**Comment by rprouse** [comment]
@CharliePoole the foundation originally asked that the top contributors for the main projects sign. Since that tends to be you and/or me for the majority of the projects and since we have a core team of decision makers, I asked that the core team be the signatories rather than round up top five contributors for 20 projects. Jon was fine with this.

To make sure I wasn't misrepresenting it, I also looked through the contributions for our top repos and the two of us account for around 90 to 95% of contributions by lines of code. The only exception is the adapter with @OsirisTerje, but he is already on the core team.

**Comment by CharliePoole** [comment]
That sounds good then. We should look further into NUnit.System.Linq though. It's not contributed by any of us, except for copying the code from Mono.

**Comment by jnm2** [comment]
Looks fine here too. :+1:

**Comment by rprouse** [comment]
Mono is already a part of the .NET Foundation, so the question of NUnit.System.Linq is probably moot 😄

**Comment by rprouse** [comment]
I have sent this list to Jon Galloway.

**Comment by ChrisMaddock** [comment]
@rprouse - can this issue be closed now? 🙂
