### ISSUE TITLE
nunit.analyser project

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/governance#34]
We need to make a decision about the future of the nunit.analyzers project.

The nunit.analyzers project was brought to the organization by @JasonBock back in 2016. Jason worked on the project for a while, however there has been little activity on the project for some time.

Back in November 2017 - @mikkelbu expressed an interest in contributing to the project, and started the discussion on the [Developer List](https://groups.google.com/forum/#!topic/nunit-developer/fTTvvzuVX1E) as to how to do this. During that process, Mikkel reached out to Jason as to how best to help - Jason's response was that unfortunately he no longer has time to work on the project, and would be happy for someone else to take over.

From here, it seems we have three options:
1) Abandon and archive the project.
2) Find a new maintainer for the project
3) Adopt the project into the responsibilities of one of the existing teams

I've since talked to Mikkel, who would be interested in taking on the maintainer role for this project. We discussed how this should involve deciding on the projects direction, and managing the associated community contributions that come to the project. (Mikkel - I'll leave you to add more on your thoughts here, if you wish!)

I'll add my personal opinions separately.

**Comment by ChrisMaddock** [comment]
In my opinion, this project needs a dedicated maintainer to grow. I would be concerned about adding to the workload of the existing teams, and how that would likely lead to the analyser project becoming neglected.

As a user of NUnit - I'd love there to be a set of analysers. Jason has done some great work on the project already, and I don't want that to go to waste. It's fair to say I've a vested interest in seeing this project succeed!

I personally think it would be a great benefit to the organization for Mikkel to take over as maintainer of the project - and I'm very happy he's interested in doing so!

**Comment by CharliePoole** [comment]
@ChrisMaddock I agree with having Mikkel be the project maintainer. I assume it continues in "experimental" status until we decide otherwise.

**Comment by ChrisMaddock** [comment]
I am proposing nothing else changing other than Mikkel taking over from Jason - so 'yes', in my opinion. 🙂

**Comment by jnm2** [comment]
Library-specific analyzers have been one of the most positive experiences I've had with any library. I'm relieved that capable hands are offering to take it up!

**Comment by rprouse** [comment]
I am fine with @mikkelbu taking over assuming it remains experimental for now. It sounds like we pretty much have consensus on this. Can we close the issue?

@mikkelbu, I have bumped up your access to the Analyzers repo to admin so that you can make changes or add members. When you feel that the project is ready for an initial release, please talk to the @nunit/core-team and we can decide how to proceed.

**Comment by mikkelbu** [comment]
@rprouse Please close the issue 😄 . My plan is the following (in more or less a random order)
* Get an idea of the existing code (both the structure of the code and which functionality it support)
* Get some more tooling (CI, build scripts, make it work in both VS15 and 17, ...)
* Write some more documentation
* Easy to add extensions/features to attract more contributors
(and I probably forgot a lot of things)

**Comment by ChrisMaddock** [comment]
Sounds like a great way to build things up. 😀

**Comment by CharliePoole** [comment]
This is great to see! Thanks for stepping up.
