### ISSUE TITLE
Changing our governance docs

### ISSUE THREAD

**Issue by CharliePoole** [nunit/governance#9]
What should be the rules about who can change these docs? I'd like to give everyone write access, but I think we should first agree on what it takes to change them.

* Does it require a vote?
* Is there a difference between simple text changes and "big" changes? If so, who decides.
* Where should we document whatever rules we agree on?

**Comment by rprouse** [comment]
I think we should lock down master so everything needs to go through a pull request for visibility. Admins could still push to master, but that should be discouraged.

Then, rules for changes (merging pull requests).

1. One @nunit/core-team member submits a pull request for review by the team
2. Spelling, grammar, or formatting changes that do not change the meaning of the document can be merged by one team member other than the member that submitted the PR
3. Any changes to the content or meaning must be voted on by the team and can only be merged when they have been approved by a majority or 2/3 of the team depending on the type of change (see our other governance documents for voting rules)
4. Ideally, PRs that require voting should state so and indicate if they require >50% or 2/3 majority
5. The core team self-polices that the rules are followed

**Comment by CharliePoole** [comment]
Makes sense to me. We can try it out on this issue.

**Comment by ChrisMaddock** [comment]
Sounds good to me.

**Comment by jnm2** [comment]
Me too.

**Comment by OsirisTerje** [comment]
ok here
